# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classify_and_extract.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63lassify_and_extract.proto\x12\tavukatjet\"\x17\n\x07Request\x12\x0c\n\x04text\x18\x01 \x01(\t\"C\n\x0f\x45xtractResponse\x12\x17\n\x0fgramOneKeywords\x18\x01 \x03(\t\x12\x17\n\x0fgramTwoKeywords\x18\x02 \x03(\t\"!\n\x10\x43lassifyResponse\x12\r\n\x05label\x18\x01 \x01(\t2\x94\x01\n\x16\x45xtractorAndClassifier\x12;\n\x07\x45xtract\x12\x12.avukatjet.Request\x1a\x1a.avukatjet.ExtractResponse\"\x00\x12=\n\x08\x43lassify\x12\x12.avukatjet.Request\x1a\x1b.avukatjet.ClassifyResponse\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_EXTRACTRESPONSE = DESCRIPTOR.message_types_by_name['ExtractResponse']
_CLASSIFYRESPONSE = DESCRIPTOR.message_types_by_name['ClassifyResponse']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'classify_and_extract_pb2'
  # @@protoc_insertion_point(class_scope:avukatjet.Request)
  })
_sym_db.RegisterMessage(Request)

ExtractResponse = _reflection.GeneratedProtocolMessageType('ExtractResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTRESPONSE,
  '__module__' : 'classify_and_extract_pb2'
  # @@protoc_insertion_point(class_scope:avukatjet.ExtractResponse)
  })
_sym_db.RegisterMessage(ExtractResponse)

ClassifyResponse = _reflection.GeneratedProtocolMessageType('ClassifyResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFYRESPONSE,
  '__module__' : 'classify_and_extract_pb2'
  # @@protoc_insertion_point(class_scope:avukatjet.ClassifyResponse)
  })
_sym_db.RegisterMessage(ClassifyResponse)

_EXTRACTORANDCLASSIFIER = DESCRIPTOR.services_by_name['ExtractorAndClassifier']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=41
  _REQUEST._serialized_end=64
  _EXTRACTRESPONSE._serialized_start=66
  _EXTRACTRESPONSE._serialized_end=133
  _CLASSIFYRESPONSE._serialized_start=135
  _CLASSIFYRESPONSE._serialized_end=168
  _EXTRACTORANDCLASSIFIER._serialized_start=171
  _EXTRACTORANDCLASSIFIER._serialized_end=319
# @@protoc_insertion_point(module_scope)
