# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import classify_and_extract_pb2 as classify__and__extract__pb2


class ExtractorAndClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/avukatjet.ExtractorAndClassifier/Extract',
                request_serializer=classify__and__extract__pb2.Request.SerializeToString,
                response_deserializer=classify__and__extract__pb2.ExtractResponse.FromString,
                )
        self.Classify = channel.unary_unary(
                '/avukatjet.ExtractorAndClassifier/Classify',
                request_serializer=classify__and__extract__pb2.Request.SerializeToString,
                response_deserializer=classify__and__extract__pb2.ClassifyResponse.FromString,
                )


class ExtractorAndClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Extract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtractorAndClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=classify__and__extract__pb2.Request.FromString,
                    response_serializer=classify__and__extract__pb2.ExtractResponse.SerializeToString,
            ),
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=classify__and__extract__pb2.Request.FromString,
                    response_serializer=classify__and__extract__pb2.ClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avukatjet.ExtractorAndClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExtractorAndClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/avukatjet.ExtractorAndClassifier/Extract',
            classify__and__extract__pb2.Request.SerializeToString,
            classify__and__extract__pb2.ExtractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/avukatjet.ExtractorAndClassifier/Classify',
            classify__and__extract__pb2.Request.SerializeToString,
            classify__and__extract__pb2.ClassifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
